### PR TITLE
Updated jwt to latest version

### PR DESCRIPTION
**Pull request by adamjgray**
@spinninti @justinhill @bsjohnson @iGoDigital-LLC/alot

### CODE REVIEW

**Comment by benjamindsnow** [comment]
Fun fact: Nathan Corn wanted me to maintain all of these different Fuel SDK's, but I wasn't into it. Are we planning on submitting a PR to ET?

**Comment by benjamindsnow** [comment]
Most of these gems don't have changelogs, but I'm gonna give this a Seems Fine™

**Comment by adamjgray** [comment]
I'm not opposed to submitting back to them, but our version isn't currently mergeable with upstream.  So there's probably a bit of work to get up-to-date with that gem before we can do that.

**Comment by justinhill** [comment]
as long as all the other repo's tests still pass after this then i'm good with it :+1:

**Pull request merged**
